### ISSUE TITLE
Impossible to download latest JAR file with new site and other regressions

### ISSUE THREAD

**Issue by proninyaroslav** [sonatype-nexus-community/search-maven-org#33]
Hi. Earlier I could make a link to download the latest JAR by adding `v=LATEST` parameter to the URL like this:
```
https://search.maven.org/remote_content?g=ru.proninyaroslav&a=java-template-engine&v=LATEST
```
Now for this I had to return to the classic version by adding `/classic/` to the URL. I think it's a good idea to add this feature to a new site. 

Also, the ability to refer to the current release using the https://maven-badges.herokuapp.com service is broken (see https://github.com/softwaremill/maven-badges/issues/20), for example:
```
https://maven-badges.herokuapp.com/maven-central/ru.proninyaroslav/java-template-engine
```

**Comment by jorlina** [comment]
In addition to other fixes, the ability to download the latest version has been restored.  I now get the right jar file when I hit:

https://search.maven.org/remote_content?g=ru.proninyaroslav&a=java-template-engine&v=LATEST

I'd like to close this issue, since the Maven badge issue should be solved once we fix #48. The Heroku app serving up the badges appears to simply redirect to a link in the old format.

```
$ curl -sIL https://maven-badges.herokuapp.com/maven-central/cz.jirutka.rsql/rsql-parser
HTTP/1.1 302 Found
Server: Cowboy
Connection: keep-alive
X-Powered-By: Express
Location: http://search.maven.org/#artifactdetails%7Ccz.jirutka.rsql%7Crsql-parser%7C2.1.0%7C
Vary: Accept
Content-Type: text/plain; charset=utf-8
Content-Length: 105
Date: Thu, 23 Aug 2018 19:24:26 GMT
Via: 1.1 vegur
```
